export const GET_ALL_SOCIAL_INTERACTIONS_SUCCESS = "GET_ALL_SOCIAL_INTERACTIONS"
export const ADD_SOCIAL_INTERACTION_SUCCESS = "ADD_SOCIAL_INTERACTION_SUCCESS"
export const UPDATE_SOCIAL_INTERACTION_SUCCESS = "UPDATE_SOCIAL_INTERACTION_SUCCESS"
export const DELETE_SOCIAL_INTERACTION_SUCCESS = "DELETE_SOCIAL_INTERACTION_SUCCESS"

export const GET_ALL_VISITED_PLACES_SUCCESS = "GET_ALL_VISITED_PLACES_SUCCESS"
export const ADD_VISITED_PLACES_SUCCESS = "ADD_VISITED_PLACES_SUCCESS"
export const UPDATE_VISITED_PLACES_SUCCESS = "UPDATE_VISITED_PLACES_SUCCESS"
export const DELETE_VISITED_PLACES_SUCCESS = "DELETE_VISITED_PLACES_SUCCESS"
